title: Positive Disruption 2021
logo: /podi/data/figs/logo.png
description: Draft results for internal analysis
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  -charts.md

theme: jekyll-theme-tactile
