title: Positive Disruption Draft Results

logo: docs/logo.png

description: Draft results for internal analysis

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: minima
